source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'YYKit','0.9.6'
#pod 'UITableView+FDTemplateLayoutCell'
pod 'GPUImage'
pod 'AFOnoResponseSerializer'
pod 'HMSegmentedControl'
#pod 'LeanCloudSDK'
pod 'ASIHTTPRequest'
#pod 'LLSlideMenu'
pod 'RESideMenu'
pod 'MMDrawerController'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'JTFadingInfoView'
#pod 'DKCarouselView'
pod 'SSKeychain'
pod 'CYLTableViewPlaceHolder'
pod 'UIViewController-KeyboardAdditions'
pod 'UIImage+BlurredFrame', '0.0.4'
pod 'BlocksKit', '2.2.5'
pod 'LBXScan'