platform :ios, '9.0'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'YYKit','0.9.6'
#pod 'UITableView+FDTemplateLayoutCell'
pod 'GPUImage'
pod 'AFOnoResponseSerializer'
pod 'HMSegmentedControl'
#pod 'LeanCloudSDK'
pod 'ASIHTTPRequest'
#pod 'LLSlideMenu'
pod 'RESideMenu'
pod 'MMDrawerController'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'JTFadingInfoView'
#pod 'DKCarouselView'
pod 'SSKeychain'
pod 'CYLTableViewPlaceHolder'